pull_request_rules:
  - name: ask devs to review PR
    conditions:
      - or:
        - base=main
        - base=dev
      - -closed
    actions:
      request_reviews:
        users:
          - QuentinCn
          - ErwanSimonetti
          - BlanchoMartin
          - HKtueur1
          - Azzzen
        random_count: 2

  - name: Automatic merge on approval
    conditions:
      - or:
        - base=main
        - base=dev
      - "#approved-reviews-by>=2"
      - "#review-threads-unresolved=0"
      - "#changes-requested-reviews-by=0"
      - label!=manual merge
    actions:
      merge:
        method: rebase