#!/bin/sh

LIB_SFML="./libsfml.so"
LIB_RTYPE="./librtype.so"
CMAKE_DIRECTORY_SFML="./modules/build"

rm -rf $CMAKE_DIRECTORY_SFML
mkdir $CMAKE_DIRECTORY_SFML && cd $CMAKE_DIRECTORY_SFML && cmake .. && cmake --build . && mv $LIB_SFML .. && mv $LIB_RTYPE .. && cd ..