#!/bin/bash

# check if the script is executed with a parameter
if [ -z "$1" ]; then
  echo "Please provide a parameter to launch a specific command."
  exit 1
fi

if [ -z "$2" ]; then
  echo "Please provide a parameter for the container name."
  exit 1
fi

# define commands to be launched based on the parameter value
case $1 in
  "buildClient")
    docker build -t rtype_client -f client/Dockerfile .
    ;;
  "buildServer")
    docker build -t rtype_server -f server/Dockerfile .
    ;;
    "runClient")
    xhost + && docker run -it --rm --name $2 --device /dev/dri -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix rtype_client && xhost -
    ;;
    "runServer")
    xhost + && docker run -it --rm --device /dev/dri --name $2 -p 1234:1234/udp -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix rtype_server && xhost -
    ;;
    "server")
    xhost + && docker build -t rtype_server -f server/Dockerfile . && docker run -it --rm --device /dev/dri --name $2 -p 1234:1234/udp -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix rtype_server && xhost -
    ;;
    "client")
    xhost + && docker build -t rtype_client -f client/Dockerfile . && docker run -it --rm --name $2 --device /dev/dri -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix rtype_client && xhost -
    ;;
  *)
    echo "Invalid parameter. Please try again with a valid parameter."
    exit 1
    ;;
esac