#!/bin/sh

BINARY_SERVER="./r-type_server"
CMAKE_DIRECTORY_SERVER="./build"

rm -rf $CMAKE_DIRECTORY_SERVER && mkdir $CMAKE_DIRECTORY_SERVER && cd $CMAKE_DIRECTORY_SERVER && cmake .. && cmake --build . && cd ../..